development:
  adapter: async

test:
  adapter: test

production:
  adapter: redis
  # This grabs the Redis To Go from the Heroku add-on
  url: <%= ENV.fetch("REDISTOGO_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: WishUpon_api_production
